const popupAddNewCard = document.querySelector('.popup__add-new-card');
const popupNewCardButton = popupAddNewCard.querySelector('.popup__button');
const openNewCardPopupButton = document.querySelector('.user-info__button');
const popupEditUserInfo = document.querySelector('.popup__edit-user-info');
const openEditUserPopupButton = document.querySelector('.user-info__edit-button');
const popupEditUserButton = popupEditUserInfo.querySelector('.popup__button');
const editForm = popupEditUserInfo.querySelector('.popup__form');
const form = popupAddNewCard.querySelector('.popup__form');
const placesList = document.querySelector('.places-list');
const popupImg = document.querySelector('.popup-img');
const popupImgBackground = popupImg.querySelector('.popup-img__background');
const errorText = 'Это обязательное поле';
const errorLengthText = 'Должно быть от 2 до 30 символов';
const errorLinkText = 'Здесь должна быть ссылка';
const inputsNewCardForm = Array.from(form.querySelectorAll('input'));
const inputsEditProfileForm = Array.from(editForm.querySelectorAll('input'));
const setSubmitNewCardButtonState = () => {setSubmitButtonState(inputsNewCardForm,popupNewCardButton)};
const setSubmitEditUserButtonState = () => {setSubmitButtonState(inputsEditProfileForm,popupEditUserButton)};